export const GET_ALL_PLAN_ASYNC = "GET_ALL_PLAN_ASYNC";
export const GET_ALL_PLAN_SUCCESS = "GET_ALL_PLAN_SUCCESS";
export const GET_ALL_PLAN_FAILURE = "GET_ALL_PLAN_FAILURE";
// get one
export const GET_ONE_PLAN_ASYNC = "GET_ONE_PLAN_ASYNC";
export const GET_ONE_PLAN_SUCCESS = "GET_ONE_PLAN_SUCCESS";
export const GET_ONE_PLAN_FAILURE = "GET_ONE_PLAN_FAILURE";
