export const UPDATE_PLAN_ASYNC = "UPDATE_PLAN_ASYNC";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";
export const UPDATE_PLAN_FAILURE = "UPDATE_PLAN_FAILURE";
export const UPDATE_STATUS_PLAN_ASYNC = "UPDATE_STATUS_PLAN_ASYNC";
export const UPDATE_STATUS_PLAN_SUCCESS = "UPDATE_STATUS_PLAN_SUCCESS";
export const UPDATE_STATUS_PLAN_FAILURE = "UPDATE_STATUS_PLAN_FAILURE";
