const AUTH_REFRSH_TOKEN_ASYNC = "AUTH_REFRSH_TOKEN_ASYNC";
const AUTH_REFRSH_TOKEN_SUCCESS = "AUTH_REFRSH_TOKEN_SUCCESS";
const AUTH_REFRSH_TOKEN_FAILURE = "AUTH_REFRSH_TOKEN_FAILURE";

export {
  AUTH_REFRSH_TOKEN_ASYNC,
  AUTH_REFRSH_TOKEN_SUCCESS,
  AUTH_REFRSH_TOKEN_FAILURE,
};
