export const DISABLE_USER_ADDRESS_ASYNC = "DISABLE_USER_ADDRESS_ASYNC";
export const DISABLE_USER_ADDRESS_SUCCESS = "DISABLE_USER_ADDRESS_SUCCESS";
export const DISABLE_USER_ADDRESS_FAILURE = "DISABLE_USER_ADDRESS_FAILURE";
