export const CREATE_OFFER_BARTER_ASYNC = "CREATE_OFFER_BARTER_ASYNC";
export const CREATE_OFFER_BARTER_SUCCESS = "CREATE_OFFER_BARTER_SUCCESS";
export const CREATE_OFFER_BARTER_FAILURE = "CREATE_OFFER_BARTER_FAILURE";
