export const UPDATE_THEME_ASYNC = "UPDATE_THEME_ASYNC";
export const UPDATE_THEME_SUCCESS = "UPDATE_THEME_SUCCESS";
export const UPDATE_THEME_FAILURE = "UPDATE_THEME_FAILURE";
export const UPDATE_STATUS_THEME_ASYNC = "UPDATE_STATUS_THEME_ASYNC";
export const UPDATE_STATUS_THEME_SUCCESS = "UPDATE_STATUS_THEME_SUCCESS";
export const UPDATE_STATUS_THEME_FAILURE = "UPDATE_STATUS_THEME_FAILURE";
