const AUTH_SET_PASS_ASYNC = "AUTH_SET_PASS_ASYNC";
const AUTH_SET_PASS_SUCCESS = "AUTH_SET_PASS_SUCCESS";
const AUTH_SET_PASS_FAILURE = "AUTH_SET_PASS_FAILURE";

export { AUTH_SET_PASS_ASYNC, AUTH_SET_PASS_SUCCESS, AUTH_SET_PASS_FAILURE };
