export const GET_ALL_OFFER_BARTER_ASYNC = "GET_ALL_OFFER_BARTER_ASYNC";
export const GET_ALL_OFFER_BARTER_SUCCESS = "GET_ALL_OFFER_BARTER_SUCCESS";
export const GET_ALL_USER_OFFER_SUCCESS = "GET_ALL_USER_OFFER_SUCCESS";
export const GET_ALL_OFFER_BARTER_FAILURE = "GET_ALL_OFFER_BARTER_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_ONE_OFFER_BARTER_ASYNC = "GET_ONE_OFFER_BARTER_ASYNC";
export const GET_ONE_OFFER_BARTER_SUCCESS = "GET_ONE_OFFER_BARTER_SUCCESS";
export const GET_ONE_OFFER_BARTER_FAILURE = "GET_ONE_OFFER_BARTER_FAILURE";
