const AUTH_REGISTER_ASYNC = "AUTH_REGISTER_ASYNC";
const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export { AUTH_REGISTER_ASYNC, AUTH_REGISTER_SUCCESS, AUTH_REGISTER_FAILURE };
