export const DELETE_OFFER_AUCTION_ASYNC = "DELETE_OFFER_AUCTION_ASYNC";
export const DELETE_OFFER_AUCTION_SUCCESS = "DELETE_OFFER_AUCTION_SUCCESS";
export const DELETE_OFFER_AUCTION_FAILURE = "DELETE_OFFER_AUCTION_FAILURE";
