const AUTH_FORGET_PASS_ASYNC = "AUTH_FORGET_PASS_ASYNC";
const AUTH_FORGET_PASS_SUCCESS = "AUTH_FORGET_PASS_SUCCESS";
const AUTH_FORGET_PASS_FAILURE = "AUTH_FORGET_PASS_FAILURE";

export { AUTH_FORGET_PASS_ASYNC, AUTH_FORGET_PASS_SUCCESS, AUTH_FORGET_PASS_FAILURE };
