export const UPDATE_INQUIRY_ASYNC = "UPDATE_INQUIRY_ASYNC";
export const UPDATE_INQUIRY_SUCCESS = "UPDATE_INQUIRY_SUCCESS";
export const UPDATE_INQUIRY_FAILURE = "UPDATE_INQUIRY_FAILURE";
export const UPDATE_STATUS_INQUIRY_ASYNC = "UPDATE_STATUS_INQUIRY_ASYNC";
export const UPDATE_STATUS_INQUIRY_SUCCESS = "UPDATE_STATUS_INQUIRY_SUCCESS";
export const UPDATE_STATUS_INQUIRY_FAILURE = "UPDATE_STATUS_INQUIRY_FAILURE";
