const state = () => ({
  list: [],
  item: {
    id: null,
    is_deleted: null,
    created_at: null,
    updated_at: null,
    created_id: null,
    updated_id: null,
    ip: null,
    is_viewed: null,
    is_active: null,
    full_name: null,
    jensiat: null,
    national_no: null,
    father_name: null,
    mobile: null,
    email: null,
    password: null,
    image_avatar: null,
    phone: null,
    money_deposit: null,
    roles: [],
  },
});
export default state;
