export const UPDATE_OFFER_AUCTION_ASYNC = "UPDATE_OFFER_AUCTION_ASYNC";
export const UPDATE_OFFER_AUCTION_SUCCESS = "UPDATE_OFFER_AUCTION_SUCCESS";
export const UPDATE_OFFER_AUCTION_FAILURE = "UPDATE_OFFER_AUCTION_FAILURE";
