export const GET_ALL_ZONE_ASYNC = "GET_ALL_ZONE_ASYNC";
export const GET_ALL_ZONE_SUCCESS = "GET_ALL_ZONE_SUCCESS";
export const GET_ALL_ZONE_FAILURE = "GET_ALL_ZONE_FAILURE";
// get one
export const GET_ONE_ZONE_ASYNC = "GET_ONE_ZONE_ASYNC";
export const GET_ONE_ZONE_SUCCESS = "GET_ONE_ZONE_SUCCESS";
export const GET_ONE_ZONE_FAILURE = "GET_ONE_ZONE_FAILURE";
