const CREATE_THEME_ASYNC = "CREATE_THEME_ASYNC";
const CREATE_THEME_SUCCESS = "CREATE_THEME_SUCCESS";
const CREATE_THEME_FAILURE = "CREATE_THEME_FAILURE";
export { CREATE_THEME_ASYNC, CREATE_THEME_SUCCESS, CREATE_THEME_FAILURE };
