export const GET_ALL_INQUIRY_ASYNC = "GET_ALL_INQUIRY_ASYNC";
export const GET_ALL_INQUIRY_SUCCESS = "GET_ALL_INQUIRY_SUCCESS";
export const GET_ALL_INQUIRY_FAILURE = "GET_ALL_INQUIRY_FAILURE";
// get one
export const GET_AN_INQUIRY_ASYNC = "GET_AN_INQUIRY_ASYNC";
export const GET_AN_INQUIRY_SUCCESS = "GET_AN_INQUIRY_SUCCESS";
export const GET_AN_INQUIRY_FAILURE = "GET_AN_INQUIRY_FAILURE";
