const TOGGLE_FORM_LOADING = "TOGGLE_FORM_LOADING";
const TOGGLE_SKELETON_LOADING = "TOGGLE_SKELETON_LOADING";

export const LOADING = "loading";

export const LOAGIND_TYPES = {
  TOGGLE_FORM_LOADING,
  TOGGLE_SKELETON_LOADING,
};
