const TOGGLE_FORM_LOADING = "TOGGLE_FORM_LOADING";
const TOGGLE_SKELETON_LOADING = "TOGGLE_SKELETON_LOADING";
const TOGGLE_SKELETON_LOADING_LIST = "TOGGLE_SKELETON_LOADING_LIST";
const TOGGLE_SKELETON_LOADING_ONE = "TOGGLE_SKELETON_LOADING_ONE";

export {
  TOGGLE_FORM_LOADING,
  TOGGLE_SKELETON_LOADING,
  TOGGLE_SKELETON_LOADING_LIST,
  TOGGLE_SKELETON_LOADING_ONE,
};
