export const DELETE_OFFER_TENDER_ASYNC = "DELETE_OFFER_TENDER_ASYNC";
export const DELETE_OFFER_TENDER_SUCCESS = "DELETE_OFFER_TENDER_SUCCESS";
export const DELETE_OFFER_TENDER_FAILURE = "DELETE_OFFER_TENDER_FAILURE";
