export const UPDATE_ROLE_ASYNC = "UPDATE_ROLE_ASYNC";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILURE = "UPDATE_ROLE_FAILURE";
export const UPDATE_STATUS_ROLE_ASYNC = "UPDATE_STATUS_ROLE_ASYNC";
export const UPDATE_STATUS_ROLE_SUCCESS = "UPDATE_STATUS_ROLE_SUCCESS";
export const UPDATE_STATUS_ROLE_FAILURE = "UPDATE_STATUS_ROLE_FAILURE";
