export const GET_ALL_OFFER_ASYNC = "GET_ALL_OFFER_ASYNC";
export const GET_ALL_OFFER_SUCCESS = "GET_ALL_OFFER_SUCCESS";
export const GET_ALL_USER_OFFER_SUCCESS = "GET_ALL_USER_OFFER_SUCCESS";
export const GET_ALL_OFFER_FAILURE = "GET_ALL_OFFER_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_AN_OFFER_ASYNC = "GET_AN_OFFER_ASYNC";
export const GET_AN_OFFER_SUCCESS = "GET_AN_OFFER_SUCCESS";
export const GET_AN_OFFER_FAILURE = "GET_AN_OFFER_FAILURE";
