export const DELETE_USER_ADDRESS_ADDRESS_ASYNC = "DELETE_USER_ADDRESS_ADDRESS_ASYNC";
export const DELETE_USER_ADDRESS_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_ADDRESS_FAILURE = "DELETE_USER_ADDRESS_ADDRESS_FAILURE";
