export const GET_ALL_CATEGORIES_ASYNC = "GET_ALL_CATEGORIES_ASYNC";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
export const GET_ONE_CATEGORY_ASYNC = "GET_ONE_CATEGORY_ASYNC";
export const GET_ONE_CATEGORY_SUCCESS = "GET_ONE_CATEGORY_SUCCESS";
export const GET_ONE_CATEGORY_FAILURE = "GET_ONE_CATEGORY_FAILURE";
