export const GET_ALL_OFFER_INQUIRY_ASYNC = "GET_ALL_OFFER_INQUIRY_ASYNC";
export const GET_ALL_OFFER_INQUIRY_SUCCESS = "GET_ALL_OFFER_INQUIRY_SUCCESS";
export const GET_ALL_USER_OFFER_SUCCESS = "GET_ALL_USER_OFFER_SUCCESS";
export const GET_ALL_OFFER_INQUIRY_FAILURE = "GET_ALL_OFFER_INQUIRY_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_ONE_OFFER_INQUIRY_ASYNC = "GET_ONE_OFFER_INQUIRY_ASYNC";
export const GET_ONE_OFFER_INQUIRY_SUCCESS = "GET_ONE_OFFER_INQUIRY_SUCCESS";
export const GET_ONE_OFFER_INQUIRY_FAILURE = "GET_ONE_OFFER_INQUIRY_FAILURE";
