export const CREATE_USER_ADDRESS_ASYNC = "CREATE_USER_ADDRESS_ASYNC";
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS";
export const CREATE_USER_ADDRESS_FAILURE = "CREATE_USER_ADDRESS_FAILURE";
