export const UPDATE_SERVICE_ASYNC = "UPDATE_SERVICE_ASYNC";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAILURE = "UPDATE_SERVICE_FAILURE";
export const UPDATE_STATUS_SERVICE_ASYNC = "UPDATE_STATUS_SERVICE_ASYNC";
export const UPDATE_STATUS_SERVICE_SUCCESS = "UPDATE_STATUS_SERVICE_SUCCESS";
export const UPDATE_STATUS_SERVICE_FAILURE = "UPDATE_STATUS_SERVICE_FAILURE";
