export const GET_ALL_OFFER_ASYNC = "GET_ALL_OFFER_ASYNC";
export const GET_ALL_OFFER_SUCCESS = "GET_ALL_OFFER_SUCCESS";
export const GET_ALL_OFFER_FAILURE = "GET_ALL_OFFER_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_ONE_OFFER_ASYNC = "GET_ONE_OFFER_ASYNC";
export const GET_ONE_OFFER_SUCCESS = "GET_ONE_OFFER_SUCCESS";
export const GET_ONE_OFFER_FAILURE = "GET_ONE_OFFER_FAILURE";
