const UPLOAD_FILE_ASYNC = "UPLOAD_FILE_ASYNC";
const UPLOAD_FILE_LOADING_TOGGLE = "UPLOAD_FILE_LOADING_TOGGLE";
const RESET_IMAGE_LIST = "RESET_IMAGE_LIST";
const SET_IMAGE_LIST = "SET_IMAGE_LIST";
export {
  UPLOAD_FILE_ASYNC,
  RESET_IMAGE_LIST,
  UPLOAD_FILE_LOADING_TOGGLE,
  SET_IMAGE_LIST,
};
