export const DELETE_OFFER_INQUIRY_ASYNC = "DELETE_OFFER_INQUIRY_ASYNC";
export const DELETE_OFFER_INQUIRY_SUCCESS = "DELETE_OFFER_INQUIRY_SUCCESS";
export const DELETE_OFFER_INQUIRY_FAILURE = "DELETE_OFFER_INQUIRY_FAILURE";
