export const DELETE_OFFER_BARTER_ASYNC = "DELETE_OFFER_BARTER_ASYNC";
export const DELETE_OFFER_BARTER_SUCCESS = "DELETE_OFFER_BARTER_SUCCESS";
export const DELETE_OFFER_BARTER_FAILURE = "DELETE_OFFER_BARTER_FAILURE";
