const TOGGLE_FORM_LOADING = "TOGGLE_FORM_LOADING";
const TOGGLE_TABLE_LOADING = "TOGGLE_TABLE_LOADING";
export const LOADING = "loading";
export const LOADING_TYPES = { TOGGLE_FORM_LOADING, TOGGLE_TABLE_LOADING };
