export const UPDATE_OFFER_BARTER_ASYNC = "UPDATE_OFFER_BARTER_ASYNC";
export const UPDATE_OFFER_BARTER_SUCCESS = "UPDATE_OFFER_BARTER_SUCCESS";
export const UPDATE_OFFER_BARTER_FAILURE = "UPDATE_OFFER_BARTER_FAILURE";
