export const GET_ALL_BARTER_ASYNC = "GET_ALL_BARTER_ASYNC";
export const GET_ALL_BARTER_SUCCESS = "GET_ALL_BARTER_SUCCESS";
export const GET_ALL_BARTER_FAILURE = "GET_ALL_BARTER_FAILURE";

// get all
export const GET_ONE_BARTER_ASYNC = "GET_ONE_BARTER_ASYNC";
export const GET_ONE_BARTER_SUCCESS = "GET_ONE_BARTER_SUCCESS";
export const GET_ONE_BARTER_FAILURE = "GET_ONE_BARTER_FAILURE";
