export const GET_ALL_BARTER_ASYNC = "GET_ALL_BARTER_ASYNC";
export const GET_ALL_BARTER_SUCCESS = "GET_ALL_BARTER_SUCCESS";
export const GET_ALL_BARTER_FAILURE = "GET_ALL_BARTER_FAILURE";

// get all
export const GET_A_BARTER_ASYNC = "GET_A_BARTER_ASYNC";
export const GET_A_BARTER_SUCCESS = "GET_A_BARTER_SUCCESS";
export const GET_A_BARTER_FAILURE = "GET_A_BARTER_FAILURE";
