const AUTH_OTP_VALIDATE_ASYNC = "AUTH_OTP_VALIDATE_ASYNC";
const AUTH_OTP_VALIDATE_SUCCESS = "AUTH_OTP_VALIDATE_SUCCESS";
const AUTH_OTP_VALIDATE_FAILURE = "AUTH_OTP_VALIDATE_FAILURE";

const AUTH_OTP_RESEND_ASYNC = "AUTH_OTP_RESEND_ASYNC";
const AUTH_OTP_RESEND_SUCCESS = "AUTH_OTP_RESEND_SUCCESS";
const AUTH_OTP_RESEND_FAILURE = "AUTH_OTP_RESEND_FAILURE";

export {
  AUTH_OTP_VALIDATE_ASYNC,
  AUTH_OTP_VALIDATE_SUCCESS,
  AUTH_OTP_VALIDATE_FAILURE, 
  //-----------------//
  AUTH_OTP_RESEND_ASYNC,
  AUTH_OTP_RESEND_SUCCESS,
  AUTH_OTP_RESEND_FAILURE,
};
