export const UPDATE_ZONE_ASYNC = "UPDATE_ZONE_ASYNC";
export const UPDATE_ZONE_SUCCESS = "UPDATE_ZONE_SUCCESS";
export const UPDATE_ZONE_FAILURE = "UPDATE_ZONE_FAILURE";
export const UPDATE_STATUS_ZONE_ASYNC = "UPDATE_STATUS_ZONE_ASYNC";
export const UPDATE_STATUS_ZONE_SUCCESS = "UPDATE_STATUS_ZONE_SUCCESS";
export const UPDATE_STATUS_ZONE_FAILURE = "UPDATE_STATUS_ZONE_FAILURE";
