export const GET_ALL_USER_ASYNC = "GET_ALL_USER_ASYNC";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";
// get one
export const GET_ONE_USER_ASYNC = "GET_ONE_USER_ASYNC";
export const GET_ONE_USER_SUCCESS = "GET_ONE_USER_SUCCESS";
export const GET_ONE_USER_FAILURE = "GET_ONE_USER_FAILURE";
