export const GET_ALL_USER_ADDRESS_ADDRESS_ASYNC = "GET_ALL_USER_ADDRESS_ADDRESS_ASYNC";
export const GET_ALL_USER_ADDRESS_ADDRESS_SUCCESS = "GET_ALL_USER_ADDRESS_ADDRESS_SUCCESS";
export const GET_ALL_USER_ADDRESS_ADDRESS_FAILURE = "GET_ALL_USER_ADDRESS_ADDRESS_FAILURE";
// get one
export const GET_ONE_USER_ADDRESS_ADDRESS_ASYNC = "GET_ONE_USER_ADDRESS_ADDRESS_ASYNC";
export const GET_ONE_USER_ADDRESS_ADDRESS_SUCCESS = "GET_ONE_USER_ADDRESS_ADDRESS_SUCCESS";
export const GET_ONE_USER_ADDRESS_ADDRESS_FAILURE = "GET_ONE_USER_ADDRESS_ADDRESS_FAILURE";
