export const CREATE_OFFER_TENDER_ASYNC = "CREATE_OFFER_TENDER_ASYNC";
export const CREATE_OFFER_TENDER_SUCCESS = "CREATE_OFFER_TENDER_SUCCESS";
export const CREATE_OFFER_TENDER_FAILURE = "CREATE_OFFER_TENDER_FAILURE";
