const SET_PERMISSION_ASYNC = "SET_PERMISSION_ASYNC";
const SET_PERMISSION_SUCCESS = "SET_PERMISSION_SUCCESS";
const SET_PERMISSION_FAILURE = "SET_PERMISSION_FAILURE";
const SET_UESR = "SET_UESR";
export {
  SET_PERMISSION_ASYNC,
  SET_PERMISSION_SUCCESS,
  SET_PERMISSION_FAILURE,
  SET_UESR,
};
