const CREATE_AUCTION_ASYNC = "CREATE_AUCTION_ASYNC";
const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
const CREATE_AUCTION_FAILURE = "CREATE_AUCTION_FAILURE";
export { CREATE_AUCTION_ASYNC, CREATE_AUCTION_SUCCESS, CREATE_AUCTION_FAILURE };
