export const GET_ALL_SALE_ASYNC = "GET_ALL_SALE_ASYNC";
export const GET_ALL_SALE_SUCCESS = "GET_ALL_SALE_SUCCESS";
export const GET_ALL_SALE_FAILURE = "GET_ALL_SALE_FAILURE";
// get one
export const GET_A_SALE_ASYNC = "GET_A_SALE_ASYNC";
export const GET_A_SALE_SUCCESS = "GET_A_SALE_SUCCESS";
export const GET_A_SALE_FAILURE = "GET_A_SALE_FAILURE";
