export const GET_ALL_ROLE_ASYNC = "GET_ALL_ROLE_ASYNC";
export const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
export const GET_ALL_ROLE_FAILURE = "GET_ALL_ROLE_FAILURE";
// get one
export const GET_ONE_ROLE_ASYNC = "GET_ONE_ROLE_ASYNC";
export const GET_ONE_ROLE_SUCCESS = "GET_ONE_ROLE_SUCCESS";
export const GET_ONE_ROLE_FAILURE = "GET_ONE_ROLE_FAILURE";
