export const CREATE_OFFER_INQUIRY_ASYNC = "CREATE_OFFER_INQUIRY_ASYNC";
export const CREATE_OFFER_INQUIRY_SUCCESS = "CREATE_OFFER_INQUIRY_SUCCESS";
export const CREATE_OFFER_INQUIRY_FAILURE = "CREATE_OFFER_INQUIRY_FAILURE";
