export const GET_ALL_CATEGORIES_ASYNC = "GET_ALL_CATEGORIES_ASYNC";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
export const GET_A_CATEGORY_ASYNC = "GET_A_CATEGORY_ASYNC";
export const GET_A_CATEGORY_SUCCESS = "GET_A_CATEGORY_SUCCESS";
export const GET_A_CATEGORY_FAILURE = "GET_A_CATEGORY_FAILURE";
