export const UPDATE_OFFER_INQUIRY_ASYNC = "UPDATE_OFFER_INQUIRY_ASYNC";
export const UPDATE_OFFER_INQUIRY_SUCCESS = "UPDATE_OFFER_INQUIRY_SUCCESS";
export const UPDATE_OFFER_INQUIRY_FAILURE = "UPDATE_OFFER_INQUIRY_FAILURE";
