export const UPLOAD_FILE_ASYNC = "UPLOAD_FILE_ASYNC";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";
export const DELETE_FILE_ASYNC = "DELETE_FILE_ASYNC";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAILURE = "DELETE_FILE_FAILURE";
