const GET_ALL_ASYNC = "GET_ALL_ASYNC";
const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
const GET_ALL_FAILURE = "GET_ALL_FAILURE";
const GET_ONE_ASYNC = "GET_ONE_ASYNC";
const GET_ONE_SUCCESS = "GET_ONE_SUCCESS";
const GET_ONE_FAILURE = "GET_ONE_FAILURE";
export {
  GET_ALL_ASYNC,
  GET_ALL_SUCCESS,
  GET_ALL_FAILURE,
  GET_ONE_ASYNC,
  GET_ONE_SUCCESS,
  GET_ONE_FAILURE,
};
