export const GET_ALL_ASYNC = "GET_ALL_ASYNC";
export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_FAILURE = "GET_ALL_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_ONE_ASYNC = "GET_ONE_ASYNC";
export const GET_ONE_SUCCESS = "GET_ONE_SUCCESS";
export const GET_ONE_FAILURE = "GET_ONE_FAILURE";
