const AUTH_LOGIN_ASYNC = "AUTH_LOGIN_ASYNC";
const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export {
  AUTH_LOGIN_ASYNC,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILURE,
};
