export const GET_ALL_TENDER_ASYNC = "GET_ALL_TENDER_ASYNC";
export const GET_ALL_TENDER_SUCCESS = "GET_ALL_TENDER_SUCCESS";
export const GET_ALL_TENDER_FAILURE = "GET_ALL_TENDER_FAILURE";
export const CHANGE_PAGE_PAGINATION = "CHANGE_PAGE_PAGINATION";
// get one
export const GET_A_TENDER_ASYNC = "GET_A_TENDER_ASYNC";
export const GET_A_TENDER_SUCCESS = "GET_A_TENDER_SUCCESS";
export const GET_A_TENDER_FAILURE = "GET_A_TENDER_FAILURE";
