export const GET_ALL_SERVICE_ASYNC = "GET_ALL_SERVICE_ASYNC";
export const GET_ALL_SERVICE_SUCCESS = "GET_ALL_SERVICE_SUCCESS";
export const GET_ALL_SERVICE_FAILURE = "GET_ALL_SERVICE_FAILURE";
// get one
export const GET_ONE_SERVICE_ASYNC = "GET_ONE_SERVICE_ASYNC";
export const GET_ONE_SERVICE_SUCCESS = "GET_ONE_SERVICE_SUCCESS";
export const GET_ONE_SERVICE_FAILURE = "GET_ONE_SERVICE_FAILURE";
