export const GET_ALL_CITIES_ASYNC = "GET_ALL_CITIES_ASYNC";
export const GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS";
export const GET_ALL_CITIES_FAILURE = "GET_ALL_CITIES_FAILURE";
export const GET_ONE_CITY_ASYNC = "GET_ONE_CITY_ASYNC";
export const GET_ONE_CITY_SUCCESS = "GET_ONE_CITY_SUCCESS";
export const GET_ONE_CITY_FAILURE = "GET_ONE_CITY_FAILURE";
