const TOGGLE_SKELETON_LOADING = "TOGGLE_SKELETON_LOADING";
const TOGGLE_SKELETON_LOADING_LIST = "TOGGLE_SKELETON_LOADING_LIST";
const TOGGLE_SKELETON_LOADING_ONE = "TOGGLE_SKELETON_LOADING_ONE";
const TOGGLE_SKELETON_LOADING_MENU = "TOGGLE_SKELETON_LOADING_MENU";
const TOGGLE_SKELETON_LOADING_DASHBOARD = "TOGGLE_SKELETON_LOADING_DASHBOARD";
export const SKELETON = "skeleton";

export const LOADING_TYPES_SKELETON = {
  TOGGLE_SKELETON_LOADING,
  
  TOGGLE_SKELETON_LOADING_LIST,
  TOGGLE_SKELETON_LOADING_ONE,
  TOGGLE_SKELETON_LOADING_MENU,
  TOGGLE_SKELETON_LOADING_DASHBOARD,
};
