export const GET_ALL_THEME_ASYNC = "GET_ALL_THEME_ASYNC";
export const GET_ALL_THEME_SUCCESS = "GET_ALL_THEME_SUCCESS";
export const GET_ALL_THEME_FAILURE = "GET_ALL_THEME_FAILURE";
// get one
export const GET_ONE_THEME_ASYNC = "GET_ONE_THEME_ASYNC";
export const GET_ONE_THEME_SUCCESS = "GET_ONE_THEME_SUCCESS";
export const GET_ONE_THEME_FAILURE = "GET_ONE_THEME_FAILURE";
