export const CREATE_OFFER_AUCTION_ASYNC = "CREATE_OFFER_AUCTION_ASYNC";
export const CREATE_OFFER_AUCTION_SUCCESS = "CREATE_OFFER_AUCTION_SUCCESS";
export const CREATE_OFFER_AUCTION_FAILURE = "CREATE_OFFER_AUCTION_FAILURE";
