export const GET_ALL_UNITS_ASYNC = "GET_ALL_UNITS_ASYNC";
export const GET_ALL_UNITS_SUCCESS = "GET_ALL_UNITS_SUCCESS";
export const GET_ALL_UNITS_FAILURE = "GET_ALL_UNITS_FAILURE";
export const GET_A_UNIT_ASYNC = "GET_A_UNIT_ASYNC";
export const GET_A_UNITS_SUCCESS = "GET_A_UNITS_SUCCESS";
export const GET_A_UNITS_FAILURE = "GET_A_UNITS_FAILURE";
