export const UPDATE_OFFER_TENDER_ASYNC = "UPDATE_OFFER_TENDER_ASYNC";
export const UPDATE_OFFER_TENDER_SUCCESS = "UPDATE_OFFER_TENDER_SUCCESS";
export const UPDATE_OFFER_TENDER_FAILURE = "UPDATE_OFFER_TENDER_FAILURE";
